<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.10.18">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Experiment Log – llm-entity-extraction</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: 1.5em;}
div.column{flex: auto;}
@media screen {
div.columns{gap: min(4vw, 1.5em);}
div.column{overflow-x: auto;}
}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-b85bc7c33db8c58e0ec93c3465666fed.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-64a204ab8560d761af7679ceaba22944.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-054c96d0537fa70bc8f6b9b071341401.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-919dda0a379ac40e641359ec180ac24f.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-054c96d0537fa70bc8f6b9b071341401.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="nav-fixed fullcontent quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="./index.html" class="navbar-brand navbar-brand-logo">
    <img src="./assets/favicon.svg" alt="" class="navbar-logo light-content">
    <img src="./assets/favicon.svg" alt="" class="navbar-logo dark-content">
    </a>
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">llm-entity-extraction</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Portal</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./experiment-log.html" aria-current="page"> 
<span class="menu-text">Experiment Log</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./kanban.html"> 
<span class="menu-text">Kanban Board</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./discussion.html"> 
<span class="menu-text">Discussion</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./../index.html"> 
<span class="menu-text">Explorer</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/Exios66/llm-entity-extraction"> <i class="bi bi-github" role="img" aria-label="Repository">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content">


<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Experiment Log</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>This page is generated from <code>reports/experiment_log.jsonl</code> on every render — the same renderer as <code>reports/experiment_log.md</code> (<code>src/experiment_log.py::render_full_log</code>), with per-document dumps omitted. Each run deep-links to its interactive detail page in the <a href="../index.html">explorer</a>.</p>
</blockquote>
<section id="index" class="level2">
<h2 class="anchored" data-anchor-id="index">Index</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Experiment</th>
<th>Task</th>
<th>Model</th>
<th>Prompt(s)</th>
<th>Headline score</th>
<th>Rows</th>
<th>Total tokens</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>qwen_qwen3.7-flash_sorter_docclass_v6_docclass_merged_ab</td>
<td>docclass_classification</td>
<td>qwen/qwen3.7-flash</td>
<td>sorter_docclass_v6</td>
<td>exact_match 0.6333</td>
<td>—</td>
<td>621037</td>
</tr>
<tr class="even">
<td>2</td>
<td>qwen_qwen3.7-flash_sorter_docclass_v7_docclass_merged_ab</td>
<td>docclass_classification</td>
<td>qwen/qwen3.7-flash</td>
<td>sorter_docclass_v7</td>
<td>exact_match 0.6667</td>
<td>—</td>
<td>652282</td>
</tr>
<tr class="odd">
<td>3</td>
<td>qwen_qwen3.7-flash_sorter_docclass_v6_docclass_ab120_s42</td>
<td>docclass_classification</td>
<td>qwen/qwen3.7-flash</td>
<td>sorter_docclass_v6</td>
<td>exact_match 0.5833</td>
<td>—</td>
<td>1873843</td>
</tr>
<tr class="even">
<td>4</td>
<td>qwen_qwen3.7-flash_sorter_docclass_v7_docclass_ab120_s42</td>
<td>docclass_classification</td>
<td>qwen/qwen3.7-flash</td>
<td>sorter_docclass_v7</td>
<td>exact_match 0.6833</td>
<td>—</td>
<td>1999237</td>
</tr>
<tr class="odd">
<td>5</td>
<td>qwen_qwen3.7-flash_contracts_specialist_docclass_v0_docclass_ab120_s42</td>
<td>docclass_specialist_extraction</td>
<td>qwen/qwen3.7-flash</td>
<td>contracts_specialist_docclass_v0</td>
<td>extraction 0.6884</td>
<td>—</td>
<td>346327</td>
</tr>
<tr class="even">
<td>6</td>
<td>qwen_qwen3.7-flash_contracts_specialist_docclass_v1_docclass_ab120_s42</td>
<td>docclass_specialist_extraction</td>
<td>qwen/qwen3.7-flash</td>
<td>contracts_specialist_docclass_v1</td>
<td>extraction 0.8444</td>
<td>—</td>
<td>655412</td>
</tr>
<tr class="odd">
<td>7</td>
<td>qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v0_docclass_ab120_s42</td>
<td>docclass_specialist_extraction</td>
<td>qwen/qwen3.7-flash</td>
<td>insurance_claims_specialist_docclass_v0</td>
<td>extraction 0.6957</td>
<td>—</td>
<td>44376</td>
</tr>
<tr class="even">
<td>8</td>
<td>qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v1_docclass_ab120_s42</td>
<td>docclass_specialist_extraction</td>
<td>qwen/qwen3.7-flash</td>
<td>insurance_claims_specialist_docclass_v1</td>
<td>extraction 0.6904</td>
<td>—</td>
<td>48609</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="qwen_qwen3.7-flash_sorter_docclass_v6_docclass_merged_ab-docclass_classification" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_sorter_docclass_v6_docclass_merged_ab-docclass_classification">qwen_qwen3.7-flash_sorter_docclass_v6_docclass_merged_ab (docclass_classification)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/1">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata">Run metadata</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T17:58:16.272567+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>sorter: sorter_docclass_v6</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>64420c6</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source" class="level3">
<h3 class="anchored" data-anchor-id="data-source">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>ground_truth</td>
<td>doc_type + doc_subclass</td>
</tr>
<tr class="odd">
<td>ground_truth_mode</td>
<td>maud_consideration_gt / s1_record_type / cuad_subtype</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>fa16e25a91631122b3e1d2111dadeca05194bcf162dd22474a2890fc83fcb7cb</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>30</td>
</tr>
<tr class="even">
<td>sample_requested</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>30</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters" class="level3">
<h3 class="anchored" data-anchor-id="parameters">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>sample</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>30</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>max_input_chars</td>
<td>100000</td>
</tr>
<tr class="even">
<td>max_tokens</td>
<td>4096</td>
</tr>
<tr class="odd">
<td>reasoning_effort</td>
<td>medium</td>
</tr>
<tr class="even">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>input_mode</td>
<td>text</td>
</tr>
<tr class="even">
<td>vision_pages</td>
<td>all</td>
</tr>
<tr class="odd">
<td>max_concurrency</td>
<td>10</td>
</tr>
<tr class="even">
<td>rate_limit_retries</td>
<td>0</td>
</tr>
<tr class="odd">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="even">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_sorter_docclass_v6_docclass_merged_ab · trace_name: docclass_classification · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage" class="level3">
<h3 class="anchored" data-anchor-id="token-usage">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores" class="level3">
<h3 class="anchored" data-anchor-id="scores">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>doc_type_accuracy</td>
<td>0.9667</td>
</tr>
<tr class="even">
<td>subclass_accuracy</td>
<td>0.6667</td>
</tr>
<tr class="odd">
<td>subclass_accuracy_equiv</td>
<td>0.6333</td>
</tr>
<tr class="even">
<td>exact_match</td>
<td>0.6333</td>
</tr>
<tr class="odd">
<td>confidence</td>
<td>0.951</td>
</tr>
<tr class="even">
<td>n_rows</td>
<td>30</td>
</tr>
<tr class="odd">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="even">
<td>equiv_recovered</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Scores — doc_type_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>hi</td>
<td>1</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>30</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.1667</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.8333</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>30</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — exact_match_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.1667</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.8</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.4667</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>30</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_class_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>contract</td>
<td>1</td>
</tr>
<tr class="even">
<td>corporate_record</td>
<td>0.9</td>
</tr>
<tr class="odd">
<td>merger_agreement</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>1</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>1</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>0.6667</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>0.2857</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>0.3333</td>
</tr>
<tr class="odd">
<td>other</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_support</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>2</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>3</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>3</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>7</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>3</td>
</tr>
<tr class="odd">
<td>other</td>
<td>1</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>2</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_confusion</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>development: 2</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>franchise: 1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>hosting: 1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>ip: 1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>manufacturing: 2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>outsourcing: 1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>supply: 1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>transportation: 1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>all_cash: 3</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>all_stock: 2 · all_cash: 1</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>articles_of_incorporation: 2 · other: 2 · bylaws: 3</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>all_stock: 2 · mixed_cash_stock: 1</td>
</tr>
<tr class="odd">
<td>other</td>
<td>all_stock: 1</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>bylaws: 1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>rights_instrument: 1 · other: 1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — input_mode_counts</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>text</td>
<td>30</td>
</tr>
</tbody>
</table>
<p><strong>Scores — sorter</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>failure_insights</td>
<td>mode_counts: {‘subclass_miss’: 10, ‘doc_type_miss’: 1} · n_failed: 11 · failures: [{‘filename’: ‘0001547903-13-000020_a41specimenclassacommonsto.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a specimen stock certificate for Class A Common Stock of NMI Holdings, Inc., presented as Exhibit 4.1. Per rule 3, the SEC exhibit wrapper is disregarded in favor of the substantive form, which is a corporate record evidencing share ownership. It does not match any of the specifically enumerated record types in rule 33, so doc_subclass is set to ‘other’. Note: contract_subtype must be null when doc_type is not contract; corrected to null.”}, {‘filename’: ‘0001078782-12-001347_s1_ex3z2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF SIMPLE PRODUCTS CORPORATION’ and contains standard internal governance provisions organized into Articles covering offices, stockholder/director meetings, officers, stock certificates, and indemnification. Per Rule 32, corporate records filed as SEC exhibits (e.g., EX-3.2) retain their substantive classification as corporate records rather than compliance filings. The title directly matches the ‘bylaws’ subclass per Rule 33.”}, {‘filename’: ‘0001615774-14-000417_s100510_ex4-6.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘rights_instrument’}, ‘predicted’: {‘doc_type’: ‘contract’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘doc_type_miss’, ‘reasoning’: “The document is a formal ‘WARRANT AGREEMENT’ executed between the issuing company and a warrant agent, detailing the issuance, exercise, redemption, adjustment, and transfer mechanics of the warrants. Its substantive form is a bilateral contract governing financial instrument terms. It does not fit any specific commercial family (e.g., license, distribution, service, or agency) and is not a corporate governance record or regulatory filing, thus classifying it as ‘other’. The SEC exhibit wrapper does not change its substantive contractual nature per rule 3.”}, {‘filename’: ‘0001144204-19-043489_tv528080_ex3-2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is labeled EXHIBIT 3.2 and contains the Organizational Minutes of the Initial Board of Directors along with the full text of the BY-LAWS OF INCUMAKER, INC. Per Rule 32, corporate governance records like bylaws attached to SEC filings as exhibits retain their substantive classification as corporate_record rather than compliance_filing. Per Rule 33, the doc_subclass is correctly identified as ‘bylaws’ based on the document’s own title. No competing signals are present.”}, {‘filename’: ‘0001469709-14-000003_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘EXHIBIT 3.2 BYLAWS’ and contains standard internal governance provisions for a Nevada corporation, including sections on shareholder meetings, board of directors, officers, and amendment procedures. Per rule 32, exhibits filed as corporate governance records are classified as corporate_record, and per rule 33, the subclass is bylaws.”}, {‘filename’: ‘0001469709-14-000529_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘powers_of_attorney’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF SWEETS &amp; TREATS, INC.’ and contains standard corporate governance provisions regarding stockholders, directors, officers, meetings, voting, and amendment procedures. Per Rule 32, corporate records such as bylaws filed as SEC exhibits (here, Exhibit 3.2) retain their substantive classification as corporate_record rather than compliance_filing. The content and exhibit wrapper confirm this classification.”}, {‘filename’: ‘0001547903-13-000006_a41specimenclassacommonsto.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a specimen stock certificate for Class A Common Stock of NMI Holdings, Inc.&nbsp;It certifies share ownership, outlines transfer and assignment procedures, and features corporate seal and officer signature blocks. Its substantive form is a corporate securities/governance instrument rather than a commercial contract or regulatory filing. Since it does not match the specific record-type subcategories listed (e.g., bylaws, articles of incorporation), it is classified as corporate_record with doc_subclass ‘other’.”}, {‘filename’: ‘contract_105_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘mixed_cash_stock’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document title is explicitly ‘AGREEMENT AND PLAN OF MERGER’. It contains classic M&amp;A deal structure provisions, including parties labeled as Parent, US Holdco, Merger Sub, and Company; dedicated articles for ‘THE MERGER’, ‘EFFECT OF THE MERGER ON CAPITAL STOCK’, representations and warranties, covenants, conditions precedent, and termination rights. The consideration mechanics reference ‘Parent Share Issuance’ and a ‘Parent Equity Conversion Ratio’ based on a ‘Cash Equivalent Consideration’ (standard for cross-border stock conversions), confirming an all-stock transaction. Under Rule 31, this is classified as a merger_agreement.”}, {‘filename’: ‘contract_145_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative machinery including ‘THE MERGER’, ‘Representations and Warranties’, ‘Conditions to the Merger’, ‘Termination’, and an ‘Exchange Ratio’ converting East Common Stock into Central Common Stock. Per Rule 31, this title and structure mandate classification as merger_agreement. The consideration section (Section 1.6) specifies that shares will be converted solely into shares of Central Common Stock (with cash provided only for fractional share interests), which aligns with the all_stock subclass.”}, {‘filename’: ‘contract_5_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘mixed_cash_stock’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A machinery: parties structured as Parent, Merger Subs, and Company; articles covering The Mergers, Reps &amp; Warranties, Conditions to Closing, No-Solicitation covenants, and Termination Payments. The consideration structure centers on an ‘Exchange Ratio’ based on the Parent’s ADS price, indicating a stock-based acquisition. Per Rule 31, this is classified as merger_agreement rather than contract.”}, {‘filename’: ‘contract_100_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative machinery including ‘THE MERGER,’ representations and warranties of the Company and Parent/Merger Sub, closing conditions, and termination provisions. The consideration section defines the Merger Consideration as ‘$56.00 in cash,’ confirming an all-cash deal. Per rules 31 and 33, this is classified as a merger_agreement with doc_subclass all_cash.”}]</td>
</tr>
</tbody>
</table>
</section>
<section id="per-subclass-accuracy-second-level-dimension" class="level3">
<h3 class="anchored" data-anchor-id="per-subclass-accuracy-second-level-dimension">Per-subclass accuracy (second-level dimension)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>subclass</th>
<th>accuracy</th>
<th>support (rows with GT)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>1</td>
<td>3</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>0.6667</td>
<td>3</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>0.2857</td>
<td>7</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>0.3333</td>
<td>3</td>
</tr>
<tr class="odd">
<td>other</td>
<td>0.0</td>
<td>1</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>0.0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
<td>2</td>
</tr>
</tbody>
</table>
<ul>
<li><p>subclass_accuracy_equiv: 0.6333 — strict subclass OR a defensible equivalent family (mixed_cash_stock ↔︎ mixed_cash_stock_election); equiv-recovered rows: none</p></li>
<li><p>input-mode split: text 30</p></li>
</ul>
<hr>
</section>
</section>
<section id="qwen_qwen3.7-flash_sorter_docclass_v7_docclass_merged_ab-docclass_classification" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_sorter_docclass_v7_docclass_merged_ab-docclass_classification">qwen_qwen3.7-flash_sorter_docclass_v7_docclass_merged_ab (docclass_classification)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/2">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata-1" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata-1">Run metadata</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T18:01:30.740514+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>sorter: sorter_docclass_v7</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>64420c6</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source-1" class="level3">
<h3 class="anchored" data-anchor-id="data-source-1">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>ground_truth</td>
<td>doc_type + doc_subclass</td>
</tr>
<tr class="odd">
<td>ground_truth_mode</td>
<td>maud_consideration_gt / s1_record_type / cuad_subtype</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>fa16e25a91631122b3e1d2111dadeca05194bcf162dd22474a2890fc83fcb7cb</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>30</td>
</tr>
<tr class="even">
<td>sample_requested</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>30</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters-1" class="level3">
<h3 class="anchored" data-anchor-id="parameters-1">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>sample</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>30</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>max_input_chars</td>
<td>100000</td>
</tr>
<tr class="even">
<td>max_tokens</td>
<td>4096</td>
</tr>
<tr class="odd">
<td>reasoning_effort</td>
<td>medium</td>
</tr>
<tr class="even">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>input_mode</td>
<td>text</td>
</tr>
<tr class="even">
<td>vision_pages</td>
<td>all</td>
</tr>
<tr class="odd">
<td>max_concurrency</td>
<td>10</td>
</tr>
<tr class="even">
<td>rate_limit_retries</td>
<td>0</td>
</tr>
<tr class="odd">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="even">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_sorter_docclass_v7_docclass_merged_ab · trace_name: docclass_classification · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage-1" class="level3">
<h3 class="anchored" data-anchor-id="token-usage-1">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores-1" class="level3">
<h3 class="anchored" data-anchor-id="scores-1">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>doc_type_accuracy</td>
<td>0.9667</td>
</tr>
<tr class="even">
<td>subclass_accuracy</td>
<td>0.7</td>
</tr>
<tr class="odd">
<td>subclass_accuracy_equiv</td>
<td>0.6667</td>
</tr>
<tr class="even">
<td>exact_match</td>
<td>0.6667</td>
</tr>
<tr class="odd">
<td>confidence</td>
<td>0.957</td>
</tr>
<tr class="even">
<td>n_rows</td>
<td>30</td>
</tr>
<tr class="odd">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="even">
<td>equiv_recovered</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Scores — doc_type_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.05</td>
</tr>
<tr class="even">
<td>hi</td>
<td>1</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.9</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>30</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.1667</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.8667</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.5333</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>30</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — exact_match_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.1667</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.8333</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>30</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_class_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>contract</td>
<td>1</td>
</tr>
<tr class="even">
<td>corporate_record</td>
<td>0.9</td>
</tr>
<tr class="odd">
<td>merger_agreement</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>1</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>1</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>0.6667</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>0.2857</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>0.6667</td>
</tr>
<tr class="odd">
<td>other</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_support</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>2</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>3</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>3</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>7</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>3</td>
</tr>
<tr class="odd">
<td>other</td>
<td>1</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>2</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_confusion</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>development: 2</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>franchise: 1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>hosting: 1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>ip: 1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>manufacturing: 2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>outsourcing: 1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>supply: 1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>transportation: 1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>all_cash: 3</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>all_stock: 2 · all_cash: 1</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>articles_of_incorporation: 2 · other: 2 · bylaws: 3</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>mixed_cash_stock: 2 · all_stock: 1</td>
</tr>
<tr class="odd">
<td>other</td>
<td>all_stock: 1</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>bylaws: 1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>rights_instrument: 1 · other: 1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — input_mode_counts</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>text</td>
<td>30</td>
</tr>
</tbody>
</table>
<p><strong>Scores — sorter</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>failure_insights</td>
<td>mode_counts: {‘subclass_miss’: 9, ‘doc_type_miss’: 1} · n_failed: 10 · failures: [{‘filename’: ‘0001547903-13-000020_a41specimenclassacommonsto.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a specimen stock certificate (Exhibit 4.1) for NMI Holdings, Inc., evidencing ownership of Class A Common Stock. It contains standard corporate governance and transfer language. Per SEC exhibit conventions, such instruments filed as exhibits are classified as corporate records. ‘Stock certificate’ is not a predefined subclass, so it defaults to ‘other’. Note: contract_subtype is set to ‘other’ per schema constraints when doc_type is not explicitly ‘contract’, but since the prompt says contract_subtype must be null when doc_type is NOT contract, I will correct that to null.”}, {‘filename’: ‘0001078782-12-001347_s1_ex3z2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF SIMPLE PRODUCTS CORPORATION’ and contains standard internal governance provisions regarding offices, stockholder meetings, board composition, officers, and amendments. Filed as Exhibit 3.2, it squarely fits the corporate_record class with the bylaws subclass per rules 32 and 33.”}, {‘filename’: ‘0001615774-14-000417_s100510_ex4-6.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘rights_instrument’}, ‘predicted’: {‘doc_type’: ‘contract’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘doc_type_miss’, ‘reasoning’: “The document is explicitly titled ‘WARRANT AGREEMENT’ and contains standard bilateral contractual provisions between a company and a warrant agent governing the issuance, exercise, redemption, and adjustment of warrants. It does not match any of the specific named contract families, placing it in the ‘other’ subgroup. Although filed as an SEC exhibit (EX-4.6), its substantive form is a private contract rather than a corporate governance record or regulatory filing.”}, {‘filename’: ‘0001144204-19-043489_tv528080_ex3-2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is filed as Exhibit 3.2 and contains organizational minutes alongside the ‘BY-LAWS OF INCUMAKER, INC.’. Per Rule 32, corporate governance records attached to SEC filings retain their substantive classification as corporate_record rather than compliance_filing. The explicit heading ‘BY-LAWS’ identifies the primary record type, triggering the bylaws subclass under Rule 33.”}, {‘filename’: ‘0001469709-14-000003_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS FOR THE REGULATION OF NIGHTFOOD HOLDINGS, INC.’ and contains standard internal governance provisions covering offices, shareholder and board meetings, officer appointments, indemnification, and amendment procedures. Filed as Exhibit 3.2, it is an internal corporate governance record per rule 32, and its subclass is determined directly from its own heading as ‘bylaws’ per rule 33.”}, {‘filename’: ‘0001469709-14-000529_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘powers_of_attorney’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF SWEETS &amp; TREATS, INC.’ and contains standard corporate governance provisions regarding stockholders, directors, officers, meetings, and amendments. Filed as Exhibit 3.2, it squarely fits the corporate_record class and bylaws subclass per rules 32 and 33.”}, {‘filename’: ‘0001547903-13-000006_a41specimenclassacommonsto.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a specimen stock certificate for NMI Holdings, Inc., filed as Exhibit 4.1. Per rule 32, corporate records attached to SEC filings retain their substantive classification as corporate records rather than compliance filings. It certifies equity ownership and outlines transfer/assignment mechanics, aligning with internal governance/capitalization records. Subclass is ‘other’ as it is a standard stock certificate not explicitly enumerated in the primary record-type list.”}, {‘filename’: ‘contract_145_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative clauses including a Merger Sub, Articles detailing the Merger mechanics, Representations &amp; Warranties, Covenants, Conditions to Closing, and Termination. The consideration section (Section 1.6) specifies that East Common Stock will be converted solely into shares of Central Common Stock (with cash only for fractional shares), indicating an all-stock transaction. Embedded exhibits (Officer’s Certificates) do not change the parent class per rule 37.”}, {‘filename’: ‘contract_5_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘mixed_cash_stock’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains the hallmark structure of a public-company acquisition agreement, including parties designated as Parent, Merger Subs, and Company, alongside detailed articles on merger mechanics, representations, covenants, conditions to closing, and termination payments. Per rule 31, this definitively falls under merger_agreement. References to Exchange Ratios, Parent ADS prices, and stock conversion mechanics indicate a stock-based consideration, supporting the all_stock subclass.”}, {‘filename’: ‘contract_100_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and follows the standard M&amp;A structure with Parent, Merger Sub, and Company parties, representations, covenants, and closing conditions. Section 1.1(iii) defines the Merger Consideration as ‘$56.00 in cash’, confirming an all-cash transaction per Rules 31 and 33.”}]</td>
</tr>
</tbody>
</table>
</section>
<section id="per-subclass-accuracy-second-level-dimension-1" class="level3">
<h3 class="anchored" data-anchor-id="per-subclass-accuracy-second-level-dimension-1">Per-subclass accuracy (second-level dimension)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>subclass</th>
<th>accuracy</th>
<th>support (rows with GT)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Development</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Franchise</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Hosting</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>IP</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Manufacturing</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Supply</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Transportation</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>all_cash</td>
<td>1</td>
<td>3</td>
</tr>
<tr class="even">
<td>all_stock</td>
<td>0.6667</td>
<td>3</td>
</tr>
<tr class="odd">
<td>articles_of_incorporation</td>
<td>0.2857</td>
<td>7</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>0.6667</td>
<td>3</td>
</tr>
<tr class="odd">
<td>other</td>
<td>0.0</td>
<td>1</td>
</tr>
<tr class="even">
<td>powers_of_attorney</td>
<td>0.0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
<td>2</td>
</tr>
</tbody>
</table>
<ul>
<li><p>subclass_accuracy_equiv: 0.6667 — strict subclass OR a defensible equivalent family (mixed_cash_stock ↔︎ mixed_cash_stock_election); equiv-recovered rows: none</p></li>
<li><p>input-mode split: text 30</p></li>
</ul>
<hr>
</section>
</section>
<section id="qwen_qwen3.7-flash_sorter_docclass_v6_docclass_ab120_s42-docclass_classification" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_sorter_docclass_v6_docclass_ab120_s42-docclass_classification">qwen_qwen3.7-flash_sorter_docclass_v6_docclass_ab120_s42 (docclass_classification)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/3">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata-2" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata-2">Run metadata</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T18:55:24.849191+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>sorter: sorter_docclass_v6</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>388c466</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source-2" class="level3">
<h3 class="anchored" data-anchor-id="data-source-2">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>ground_truth</td>
<td>doc_type + doc_subclass</td>
</tr>
<tr class="odd">
<td>ground_truth_mode</td>
<td>maud_consideration_gt / s1_record_type / cuad_subtype</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>05f05e9f45ce67c9880884f0378652369fda1782ebcd3141cfeea0259c1c490b</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>120</td>
</tr>
<tr class="even">
<td>sample_requested</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters-2" class="level3">
<h3 class="anchored" data-anchor-id="parameters-2">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>sample</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>max_input_chars</td>
<td>100000</td>
</tr>
<tr class="even">
<td>max_tokens</td>
<td>4096</td>
</tr>
<tr class="odd">
<td>reasoning_effort</td>
<td>medium</td>
</tr>
<tr class="even">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>input_mode</td>
<td>text</td>
</tr>
<tr class="even">
<td>vision_pages</td>
<td>all</td>
</tr>
<tr class="odd">
<td>max_concurrency</td>
<td>13</td>
</tr>
<tr class="even">
<td>rate_limit_retries</td>
<td>0</td>
</tr>
<tr class="odd">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="even">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_sorter_docclass_v6_docclass_ab120_s42 · trace_name: docclass_classification · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage-2" class="level3">
<h3 class="anchored" data-anchor-id="token-usage-2">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores-2" class="level3">
<h3 class="anchored" data-anchor-id="scores-2">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>doc_type_accuracy</td>
<td>0.9917</td>
</tr>
<tr class="even">
<td>subclass_accuracy</td>
<td>0.5917</td>
</tr>
<tr class="odd">
<td>subclass_accuracy_equiv</td>
<td>0.5833</td>
</tr>
<tr class="even">
<td>exact_match</td>
<td>0.5833</td>
</tr>
<tr class="odd">
<td>confidence</td>
<td>0.9445</td>
</tr>
<tr class="even">
<td>n_rows</td>
<td>120</td>
</tr>
<tr class="odd">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="even">
<td>equiv_recovered</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Scores — doc_type_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.0125</td>
</tr>
<tr class="even">
<td>hi</td>
<td>1</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.975</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>120</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.0875</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.675</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.5</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>120</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — exact_match_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.0917</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.675</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.4917</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>120</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_class_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>contract</td>
<td>1</td>
</tr>
<tr class="even">
<td>corporate_record</td>
<td>0.9583</td>
</tr>
<tr class="odd">
<td>correspondence</td>
<td>1</td>
</tr>
<tr class="even">
<td>insurance_claim</td>
<td>1</td>
</tr>
<tr class="odd">
<td>merger_agreement</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>1</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>1</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>1</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>1</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>1</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>1</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>0.8</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>1</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>0.5833</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>0.25</td>
</tr>
<tr class="even">
<td>demand</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>email</td>
<td>1</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>1</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>other</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>1</td>
</tr>
<tr class="even">
<td>pde</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>0.5</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_support</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>2</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>4</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>2</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>4</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>2</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>5</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>2</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>12</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>1</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>4</td>
</tr>
<tr class="even">
<td>demand</td>
<td>2</td>
</tr>
<tr class="odd">
<td>email</td>
<td>4</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>8</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>5</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>3</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>2</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>5</td>
</tr>
<tr class="even">
<td>other</td>
<td>17</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>6</td>
</tr>
<tr class="even">
<td>pde</td>
<td>6</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>2</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>2</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>8</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_confusion</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>agency: 2</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>co_branding: 1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>collaboration: 4</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>endorsement: 1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>franchise: 2</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>hosting: 4</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>license: 2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>outsourcing: 1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>reseller: 1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>sponsorship: 2</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>strategic_alliance: 2</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>supply: 1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>transportation: 1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>all_cash: 4 · other: 1</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>all_stock: 2</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>articles_of_incorporation: 7 · other: 1 · bylaws: 4</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>email: 1</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>bylaws: 1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>carrier: 1 · other: 2 · outpatient: 1</td>
</tr>
<tr class="even">
<td>demand</td>
<td>memo: 1 · email: 1</td>
</tr>
<tr class="odd">
<td>email</td>
<td>email: 4</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>inpatient: 8</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>letter: 2 · email: 3</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>notice: 1 · email: 2</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>notice: 1 · email: 1</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>mixed_cash_stock: 1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>email: 3 · notice: 2</td>
</tr>
<tr class="even">
<td>other</td>
<td>articles_of_incorporation: 1 · all_cash: 12 · all_stock: 3 · mixed_cash_stock: 1</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>outpatient: 6</td>
</tr>
<tr class="even">
<td>pde</td>
<td>other: 6</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>bylaws: 2</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>email: 1 · press_release: 1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>rights_instrument: 7 · other: 1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — input_mode_counts</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>text</td>
<td>120</td>
</tr>
</tbody>
</table>
<p><strong>Scores — sorter</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>failure_insights</td>
<td>mode_counts: {‘subclass_miss’: 49, ‘doc_type_miss’: 1} · n_failed: 50 · failures: [{‘filename’: ‘0001615774-14-000417_s100510_ex3-1.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is titled ‘Amended and Restated Memorandum and Articles of Association’ and filed as SEC Exhibit 3.1. Per rule 32, corporate governance documents filed as exhibits retain their substantive classification as corporate records. The content establishes the company’s name, registered office, share capital, and internal governance structure, functioning as the jurisdictional equivalent of articles of incorporation.”}, {‘filename’: ‘0001547903-13-000020_a41specimenclassacommonsto.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a specimen stock certificate (Exhibit 4.1) issued by NMI Holdings, Inc.&nbsp;It certifies ownership of Class A Common Stock, outlines transfer procedures, and references the company’s governing documents. This format and content are characteristic of corporate records documenting equity issuance and securityholder rights, fitting the corporate_record class rather than contract, merger_agreement, correspondence, or insurance_claim.”}, {‘filename’: ‘0001469709-14-000003_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘EXHIBIT 3.2 BYLAWS’ and contains standard corporate governance provisions (offices, shareholder meetings, board of directors, officers, amendments). Per rule 32, corporate records filed as SEC exhibits retain their substantive form, making this a corporate_record with doc_subclass ‘bylaws’.”}, {‘filename’: ‘0001062993-15-000198_s1011515_ex3z2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘powers_of_attorney’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF REVENUE.COM CORPORATION’ and contains standard internal governance provisions for stockholders, directors, officers, capital stock, and indemnification. Although filed as SEC Exhibit 3.2, Rule 32 dictates that such exhibits retain their substantive classification as corporate records rather than compliance filings. The content directly matches the ‘bylaws’ subclass.”}, {‘filename’: ‘0001547903-13-000006_a45warrantno1fbrcapitalmar.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘rights_instrument’}, ‘predicted’: {‘doc_type’: ‘contract’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘doc_type_miss’, ‘reasoning’: “The document is a standalone Warrant Agreement filed as SEC Exhibit 4.5. It establishes a formal agreement between NMI Holdings, Inc.&nbsp;and FBR Capital Markets &amp; Co., detailing the right to purchase common stock, exercise mechanics, anti-dilution adjustments, and transfer restrictions. As it does not align with any of the specified commercial contract families, it is classified as ‘other’ under the contract category.”}, {‘filename’: ‘0001144204-19-043489_tv528080_ex3-2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document contains the Organizational Minutes and the full text of the ‘By-Laws of Incumaker, Inc.’, filed as SEC Exhibit 3.2. Per Rule 32, corporate governance records like bylaws attached as exhibits are classified as corporate_record. Per Rule 33, the doc_subclass is bylaws based on the explicit title within the document. No contract or other class signals are present.”}, {‘filename’: ‘0001079974-08-000839_artdimensionss1x32_9252008.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF ARTDIMENSIONS, INC.’ and filed as SEC Exhibit 3.2. Its substantive content covers standard corporate governance provisions including principal offices, registered agent, stockholder and director meetings, officer roles, capital stock, dividends, and indemnification. Per rules 32 and 33, the SEC exhibit wrapper does not change the substantive form, which is a corporate record classified as bylaws.”}, {‘filename’: ‘0001144204-19-030811_tv521467_ex3-2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is filed as SEC Exhibit 3.2 and contains the Organizational Minutes of the Initial Board of Directors followed by the complete ‘BY-LAWS OF INCUMAKER, INC.’ Per Rule 32, corporate records like bylaws attached as SEC exhibits are classified as corporate_record. Per Rule 33, the subclass is bylaws based on the document’s own title and content.”}, {‘filename’: ‘0001469709-14-000529_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘powers_of_attorney’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF SWEETS &amp; TREATS, INC.’ and filed as SEC Exhibit 3.2. It contains standard corporate governance provisions covering stockholders, directors, officers, meetings, voting, and amendment procedures. Per rules 32 and 33, this is classified as a corporate_record with the subclass bylaws.”}, {‘filename’: ‘shackleton-s/all_documents/3774.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is an internal business email coordinating the execution and routing of attached notices and letters. It features standard email phrasing (‘To catch everyone up’, ‘I will be out of the office’), direct routing instructions to multiple parties, and a professional signature block with contact details, firmly placing it in the correspondence class.”}, {‘filename’: ‘hyatt-k/to_do/51.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘demand’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘memo’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document consists solely of a task assignment header with administrative fields (status, priority, dates). It lacks substantive legal language, contractual obligations, or corporate governance content. Given the limited options, it best fits correspondence as an internal administrative memo/note. Confidence is low due to the minimal content and absence of clear legal context.’}, {‘filename’: ‘ermis-f/all_documents/303.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘meeting_request’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The text is a standalone corporate disclaimer clarifying the operational and regulatory separation between PG&amp;E National Energy Group and the regulated utility. It functions as a business notice or email accompanying an invitation, lacking any contractual, corporate governance, M&amp;A, or insurance claim characteristics.’}, {‘filename’: ‘taylor-m/all_documents/7663.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘press_release’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is an email forwarding a press release regarding bankruptcy legislation. It contains standard email routing headers (‘Forwarded by…’, ‘To:’, ‘Subject:’) and includes the full text of a press release, matching the correspondence class.”}, {‘filename’: ‘sanders-r/inbox/38.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘meeting_request’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a business email discussing litigation strategy, due diligence, and scheduling meetings with the plaintiff. It explicitly refers to itself as ‘this email’ and includes a standard email confidentiality notice at the end, firmly placing it in the correspondence category.”}, {‘filename’: ‘dasovich-j/all_documents/3005.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘meeting_request’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is an internal business email with standard headers (To, cc, Subject) requesting meeting availability for a specific date. It clearly matches the correspondence class and specifically functions as an email/meeting request.’}, {‘filename’: ‘campbell-l/inbox/618.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘letter’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is an automated commercial email/notification from 1-800 CONTACTS to a customer regarding re-ordering contact lenses. It contains standard email formatting, a direct greeting, a secure link for ordering, customer support contact information, and an unsubscribe instruction, clearly fitting the correspondence class with an email subclass.’}, {‘filename’: ‘sanders-r/px/17.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘attorney_demand’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is an internal email circulating revisions to a draft arbitration demand letter among committee members. Its format, salutation, and transmittal language clearly identify it as email correspondence rather than the underlying demand letter itself.’}, {‘filename’: ‘shackleton-s/inbox/675.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘memo’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly formatted as a formal notice (labeled ‘Notice # 02-46’) with standard TO/FROM/RE headers, communicating procedural instructions to exchange members. It squarely fits the correspondence class.”}, {‘filename’: ‘kean-s/all_documents/1990.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘memo’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The text is a brief internal communication/email discussing the distribution of a regulatory analysis memo to a stakeholder committee and government officials. It lacks any contractual, corporate, M&amp;A, or insurance claim characteristics, fitting squarely into the correspondence category.’}, {‘filename’: ‘schoolcraft-d/inbox/junk/351.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘demand’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a weekly industry newsletter/email digest from Rigzone featuring oil &amp; gas headlines, market prices, event listings, and subscription management instructions. It contains no operative legal terms, agreements, or claims, squarely fitting the correspondence class as an email.’}, {‘filename’: ‘storey-g/sent_items/76.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a chain of internal corporate emails discussing terms for commodity trading confirmations (gas delivery points and pipeline nomination deadlines). It lacks operative contract language and clearly fits the correspondence class.’}, {‘filename’: ‘campbell-l/all_documents/1428.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a direct email notification from a customer relations representative to a discussion list regarding scheduled system maintenance. It lacks contractual, corporate, or M&amp;A elements, fitting squarely into the correspondence class as an operational email.’}, {‘filename’: ‘kaminski-v/inbox/81.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘letter’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a direct email exchange between two academics discussing conference travel and a seminar invitation. It features standard email formatting, conversational tone, and lacks any operative legal clauses, corporate governance records, or M&amp;A/insurance structures.’}, {‘filename’: ‘staab-t/deleted_items/418.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘letter’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a direct email from an executive to a specific recipient, containing standard email headers/footers (Message-Id, subscribe/unsubscribe instructions, ‘This email has been sent to…’). The content is a customer/stakeholder update regarding an aviation incident and precautionary inspections, fitting the correspondence class perfectly. No contractual or corporate record elements are present.”}, {‘filename’: ‘pde:233634491375303.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘pde’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a Medicare Part D pharmacy statement containing a coverage determination (‘APPROVED’), prescription details, and cost-share breakdown. This directly aligns with the insurance_claim class, which encompasses coverage determinations and EOB-style claim documents.”}, {‘filename’: ‘carrier:887993387407016.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘carrier’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘MEDICARE SUMMARY NOTICE – PHYSICIAN/SUPPLIER CLAIM’ and contains standard claim adjudication details including beneficiary information, service dates, HCPCS codes, allowed/paid amounts, and a coverage determination. This matches the insurance_claim class (EOB/adjudication notice). Doc_subclass is set to other as it does not fit the specific carrier/pde/outpatient/inpatient categories.”}, {‘filename’: ‘pde:233804493732348.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘pde’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a pharmacy statement and coverage determination for a Medicare Part D prescription drug claim, containing beneficiary details, prescription information, cost-sharing breakdown, and an explicit ‘APPROVED’ coverage outcome. This matches the format and content of an insurance claim document.”}, {‘filename’: ‘carrier:887433385493589.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘carrier’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a Medicare Summary Notice detailing a physician/supplier claim, including adjudication results, allowed/paid amounts, and a coverage determination (‘APPROVED’). This squarely matches the insurance_claim category. Subclass is set to ‘other’ as it functions as a standard EOB/summary notice rather than fitting the specific inpatient, outpatient, PDE, or carrier sub-types.”}, {‘filename’: ‘pde:233934491832935.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘pde’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a Medicare Part D pharmacy statement detailing a prescription fill, cost share, and explicitly includes a ‘COVERAGE DETERMINATION: APPROVED’ section. This format and content directly match insurance claim documentation, specifically an EOB or coverage determination record.”}, {‘filename’: ‘pde:233714489398465.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘pde’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a Medicare Part D pharmacy statement containing beneficiary details, prescription information, cost-sharing breakdown, and a coverage determination (‘APPROVED’). This directly matches the insurance_claim class, specifically functioning as an EOB or coverage determination record.”}, {‘filename’: ‘carrier:887413386039256.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘carrier’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘outpatient’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a Medicare Summary Notice for a physician/supplier claim, containing claim adjudication details, itemized service lines, payment amounts, and a coverage determination (‘APPROVED’). This aligns directly with the insurance_claim category, which encompasses claim documentation and coverage determinations.”}, {‘filename’: ‘pde:233464489735061.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘pde’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a Medicare Part D pharmacy statement detailing a prescription fill, cost share, and explicitly includes a ‘COVERAGE DETERMINATION: APPROVED’. This directly matches the insurance_claim category, which covers claim documentation, EOB statements, and coverage determinations.”}, {‘filename’: ‘pde:233114489887590.txt’, ‘expected’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘pde’}, ‘predicted’: {‘doc_type’: ‘insurance_claim’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a Medicare Part D pharmacy statement/EOB detailing an insured beneficiary, prescription details, cost share, and a coverage determination (‘APPROVED’). This directly matches the insurance_claim class, which encompasses EOB statements and coverage determinations.”}, {‘filename’: ‘contract_123_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and details a tender offer followed by a statutory merger between Safari Parent, Inc., Safari Merger Subsidiary, Inc., and Seacor Holdings Inc.&nbsp;It contains standard M&amp;A operative machinery including representations and warranties, conditions to closing, termination covenants, and specifies that shares will be converted into a fixed cash amount ($41.50 per share). Per Rule 31, this title and structure mandate the merger_agreement class. The consideration is exclusively cash, triggering the all_cash subclass under Rule 33. Embedded corporate records (e.g., Exhibit A Certificate of Incorporation) are governed by Rule 34 and do not change the parent classification.”}, {‘filename’: ‘contract_50_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative machinery, including a Parent/Merger Sub structure, Effective Time mechanics, merger consideration, representations and warranties, and closing conditions. Per rule 31, this squarely fits the merger_agreement class. Sections 2.1(d) and 2.2(d) specify that eligible shares will be converted into the right to receive a fixed amount in cash (amended in the attached schedule to $12.15 and $8.35 per share respectively), with no stock component, satisfying the all_cash subclass definition under rule 33.”}, {‘filename’: ‘contract_119_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and follows the standard M&amp;A structure with defined parties (Company, Parent, Merger Subsidiary), Articles covering the Merger mechanics, Conversion of Shares, extensive Representations and Warranties, Conditions to Closing, and Termination provisions. Section 2.02 specifies that each share of Company Stock will be converted into the right to receive ‘$58.00 in cash’, establishing an all-cash consideration. Under Rules 31 and 33, this squarely fits the merger_agreement class with an all_cash subclass.”}, {‘filename’: ‘contract_26_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains classic M&amp;A machinery: a ‘Parent’ and ‘Merger Sub’ counterparty, detailed representations and warranties, conditions to closing, termination fees, and no-shop/solicitation covenants. This directly triggers Rule 31 for merger_agreement. The transaction is funded through referenced Debt and Equity Commitment Letters and third-party Guarantors, which is characteristic of a private equity-led cash acquisition rather than a stock-based exchange, supporting the all_cash subclass.”}, {‘filename’: ‘contract_113_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A deal structure provisions, including a tender offer, merger mechanics, capital stock conversion, extensive representations and warranties, covenants, and closing conditions. The consideration is explicitly stated as ‘$22.50 per Share… in cash’, aligning with the all_cash subclass.”}, {‘filename’: ‘contract_69_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and follows the standard structure of an M&amp;A transaction agreement, including articles for the Merger, Delivery of Merger Consideration, Representations and Warranties, Covenants, Conditions to Closing, and Termination. The consideration section defines the ‘Per Share Merger Consideration’ as ‘$156.00 per Share in cash,’ confirming an all-cash deal. This squarely fits the merger_agreement class with an all_cash subclass.”}, {‘filename’: ‘contract_120_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains classic M&amp;A operative machinery: parties designated as ‘Parent’ and ‘Merger Sub’, sections on ‘The Merger’ and ‘Effective Time’, extensive representations and warranties, no-shop/fiduciary out covenants, and termination fees. Per Rule 31, this title and structure strictly dictate the merger_agreement class. The deal structure reflects a private-equity-led acquisition (Mirasol Parent/Thoma Bravo acquiring RealPage), which utilizes cash consideration, justifying the all_cash subclass.”}, {‘filename’: ‘contract_22_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A machinery including a Parent, Merger Sub, and Company, with sections detailing the merger effective time, capital stock conversion, extensive representations and warranties, covenants, conditions to closing, and termination rights. Section 4.1(a) and 4.3 specify the merger consideration as ‘$25.75 per Share in cash’, making it an all-cash transaction. Embedded corporate documents like Annex B do not alter the parent classification per rule 34.”}, {‘filename’: ‘contract_16_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A deal structure machinery: a Parent/Merger Sub counterparty setup, Effective Time/Closing mechanics, extensive Representations and Warranties, no-shop/termination covenants, and disclosure schedules. Per Rule 31, this squarely falls under merger_agreement. Section 3.1(a)(i) specifies that each share of Common Stock shall convert into the right to receive ‘$56.00 in cash’, indicating an all-cash consideration structure, which triggers doc_subclass ‘all_cash’ per Rule 33.”}, {‘filename’: ‘contract_110_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A deal structure provisions, including parties designated as ‘Parent’ and ‘Merger Sub’, articles detailing ‘THE MERGER’, ‘MERGER CONSIDERATION’, extensive representations and warranties, covenants, closing conditions, and termination fees. This directly triggers rule 31 for the merger_agreement class. The specific form of merger consideration (cash vs.&nbsp;stock) is not detailed in the provided excerpt, so ‘other’ is assigned for doc_subclass per rule 33.”}, {‘filename’: ‘contract_93_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A deal structure provisions, including merger mechanics, stock exchange ratios, representations and warranties, covenants, and termination clauses. Under rule 31, this squarely falls under merger_agreement. The consideration section specifies that Company Common Stock will be converted into an exchange ratio of Buyer Common Stock (0.275 shares), indicating an all-stock transaction, which sets doc_subclass to all_stock.”}, {‘filename’: ‘contract_68_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A deal machinery, including a Parent and Merger Sub structure, Effective Time mechanics, exchange ratios for stock consideration, extensive representations and warranties, and closing conditions. Per Rule 31, this triggers the merger_agreement class. The consideration section specifies conversion of Company Common Stock into shares of Parent Common Stock, indicating an all-stock consideration type per Rule 33. Ancillary registration rights and adoption agreements are treated as embedded annexes and do not alter the primary classification.”}, {‘filename’: ‘contract_141_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative provisions, including a ‘Merger Sub’, ‘Effective Time’, share conversion mechanics, extensive representations and warranties, conditions to closing, and termination fees. Section 2.1(a) specifies that each share of Company Common Stock will be converted into ‘$177.50 in cash’, indicating an all-cash consideration structure. Under Rule 31 and Rule 33, this clearly classifies as a merger_agreement with an all_cash subclass.”}, {‘filename’: ‘contract_31_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and follows the standard M&amp;A structure with a Parent, Merger Sub, and Target Company. Article II outlines the merger mechanics, while Article III specifies that each share of Company Common Stock will be converted into a fixed number of shares of Parent Common Stock (Exchange Ratio of 1.46), with only standard cash-in-lieu-of-fractions provisions. This confirms an all-stock consideration structure, satisfying rule 31 for merger_agreement and rule 33 for doc_subclass.”}, {‘filename’: ‘contract_9_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AMENDED AND RESTATED AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative machinery, including a cash tender offer, merger mechanics, representations and warranties, covenants, conditions precedent, and termination provisions. The consideration is strictly cash ($37.00 per share), satisfying the all_cash subclass criteria under Rule 33.”}, {‘filename’: ‘contract_76_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘mixed_cash_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative machinery including the mergers, conversion of shares, representations and warranties, covenants, conditions, and termination. Section 2.1 specifies that shareholders will receive both Parent Common Shares and $90.00 in cash per share, indicating a mixed cash and stock consideration. Thus, it fits the merger_agreement class with doc_subclass mixed_cash_stock.”}, {‘filename’: ‘contract_59_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A deal structure machinery, including a Parent/Merger Sub counterparty setup, Effective Time mechanics, extensive representations and warranties, conditions precedent, and termination covenants. Section 2.1 specifies that each share of common stock will be converted into the right to receive $19.25 in cash, confirming an all-cash consideration type. Per Rule 31 and Rule 33, this is classified as a merger_agreement with doc_subclass all_cash.”}]</td>
</tr>
</tbody>
</table>
</section>
<section id="per-subclass-accuracy-second-level-dimension-2" class="level3">
<h3 class="anchored" data-anchor-id="per-subclass-accuracy-second-level-dimension-2">Per-subclass accuracy (second-level dimension)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>subclass</th>
<th>accuracy</th>
<th>support (rows with GT)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>0.8</td>
<td>5</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>0.5833</td>
<td>12</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>0.0</td>
<td>1</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>0.25</td>
<td>4</td>
</tr>
<tr class="even">
<td>demand</td>
<td>0.0</td>
<td>2</td>
</tr>
<tr class="odd">
<td>email</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>1</td>
<td>8</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>0.4</td>
<td>5</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>0.0</td>
<td>3</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>0.0</td>
<td>2</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>0.4</td>
<td>5</td>
</tr>
<tr class="even">
<td>other</td>
<td>0.0</td>
<td>17</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>1</td>
<td>6</td>
</tr>
<tr class="even">
<td>pde</td>
<td>0.0</td>
<td>6</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>0.0</td>
<td>2</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>0.5</td>
<td>2</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
<td>8</td>
</tr>
</tbody>
</table>
<ul>
<li><p>subclass_accuracy_equiv: 0.5833 — strict subclass OR a defensible equivalent family (mixed_cash_stock ↔︎ mixed_cash_stock_election); equiv-recovered rows: none</p></li>
<li><p>input-mode split: text 120</p></li>
</ul>
<hr>
</section>
</section>
<section id="qwen_qwen3.7-flash_sorter_docclass_v7_docclass_ab120_s42-docclass_classification" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_sorter_docclass_v7_docclass_ab120_s42-docclass_classification">qwen_qwen3.7-flash_sorter_docclass_v7_docclass_ab120_s42 (docclass_classification)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/4">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata-3" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata-3">Run metadata</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T18:56:53.692191+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>sorter: sorter_docclass_v7</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>388c466</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source-3" class="level3">
<h3 class="anchored" data-anchor-id="data-source-3">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>ground_truth</td>
<td>doc_type + doc_subclass</td>
</tr>
<tr class="odd">
<td>ground_truth_mode</td>
<td>maud_consideration_gt / s1_record_type / cuad_subtype</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>05f05e9f45ce67c9880884f0378652369fda1782ebcd3141cfeea0259c1c490b</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>120</td>
</tr>
<tr class="even">
<td>sample_requested</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters-3" class="level3">
<h3 class="anchored" data-anchor-id="parameters-3">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>datasets</td>
<td>mailroom-maud-contracts,mailroom-cuad-contracts-full,mailroom-s1-corporate-records</td>
</tr>
<tr class="even">
<td>sample</td>
<td>0</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>max_input_chars</td>
<td>100000</td>
</tr>
<tr class="even">
<td>max_tokens</td>
<td>4096</td>
</tr>
<tr class="odd">
<td>reasoning_effort</td>
<td>medium</td>
</tr>
<tr class="even">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="odd">
<td>input_mode</td>
<td>text</td>
</tr>
<tr class="even">
<td>vision_pages</td>
<td>all</td>
</tr>
<tr class="odd">
<td>max_concurrency</td>
<td>13</td>
</tr>
<tr class="even">
<td>rate_limit_retries</td>
<td>0</td>
</tr>
<tr class="odd">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="even">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_sorter_docclass_v7_docclass_ab120_s42 · trace_name: docclass_classification · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage-3" class="level3">
<h3 class="anchored" data-anchor-id="token-usage-3">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores-3" class="level3">
<h3 class="anchored" data-anchor-id="scores-3">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>doc_type_accuracy</td>
<td>0.9917</td>
</tr>
<tr class="even">
<td>subclass_accuracy</td>
<td>0.6917</td>
</tr>
<tr class="odd">
<td>subclass_accuracy_equiv</td>
<td>0.6833</td>
</tr>
<tr class="even">
<td>exact_match</td>
<td>0.6833</td>
</tr>
<tr class="odd">
<td>confidence</td>
<td>0.9547</td>
</tr>
<tr class="even">
<td>n_rows</td>
<td>120</td>
</tr>
<tr class="odd">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="even">
<td>equiv_recovered</td>
<td>—</td>
</tr>
</tbody>
</table>
<p><strong>Scores — doc_type_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.0125</td>
</tr>
<tr class="even">
<td>hi</td>
<td>1</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.975</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>120</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_accuracy_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.0792</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.7667</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.6083</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>120</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — exact_match_ci</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>half</td>
<td>0.0791</td>
</tr>
<tr class="even">
<td>hi</td>
<td>0.7583</td>
</tr>
<tr class="odd">
<td>lo</td>
<td>0.6</td>
</tr>
<tr class="even">
<td>method</td>
<td>percentile-bootstrap</td>
</tr>
<tr class="odd">
<td>n</td>
<td>120</td>
</tr>
<tr class="even">
<td>n_boot</td>
<td>2000</td>
</tr>
<tr class="odd">
<td>seed</td>
<td>42</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_class_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>contract</td>
<td>1</td>
</tr>
<tr class="even">
<td>corporate_record</td>
<td>0.9583</td>
</tr>
<tr class="odd">
<td>correspondence</td>
<td>1</td>
</tr>
<tr class="even">
<td>insurance_claim</td>
<td>1</td>
</tr>
<tr class="odd">
<td>merger_agreement</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_accuracy</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>1</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>1</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>1</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>1</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>1</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>1</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>0.8</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>1</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>0.5833</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>1</td>
</tr>
<tr class="even">
<td>demand</td>
<td>0.0</td>
</tr>
<tr class="odd">
<td>email</td>
<td>1</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>1</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>0.3333</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>0.4</td>
</tr>
<tr class="even">
<td>other</td>
<td>0.0588</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>1</td>
</tr>
<tr class="even">
<td>pde</td>
<td>1</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>0.0</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>1</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — per_subclass_support</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>2</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>4</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>2</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>4</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>2</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>5</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>2</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>12</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>1</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>4</td>
</tr>
<tr class="even">
<td>demand</td>
<td>2</td>
</tr>
<tr class="odd">
<td>email</td>
<td>4</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>8</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>5</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>3</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>2</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>5</td>
</tr>
<tr class="even">
<td>other</td>
<td>17</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>6</td>
</tr>
<tr class="even">
<td>pde</td>
<td>6</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>2</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>2</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>8</td>
</tr>
</tbody>
</table>
<p><strong>Scores — subclass_confusion</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>agency: 2</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>co_branding: 1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>collaboration: 4</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>endorsement: 1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>franchise: 2</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>hosting: 4</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>license: 2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>outsourcing: 1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>reseller: 1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>sponsorship: 2</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>strategic_alliance: 2</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>supply: 1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>transportation: 1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>all_cash: 4 · other: 1</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>all_stock: 2</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>articles_of_incorporation: 7 · rights_instrument: 1 · bylaws: 4</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>email: 1</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>bylaws: 1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>carrier: 4</td>
</tr>
<tr class="even">
<td>demand</td>
<td>memo: 1 · email: 1</td>
</tr>
<tr class="odd">
<td>email</td>
<td>email: 4</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>inpatient: 8</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>letter: 2 · email: 3</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>letter: 1 · email: 1 · meeting_request: 1</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>notice: 1 · email: 1</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>mixed_cash_stock: 1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>email: 3 · notice: 2</td>
</tr>
<tr class="even">
<td>other</td>
<td>articles_of_incorporation: 1 · all_cash: 11 · other: 1 · all_stock: 3 · mixed_cash_stock: 1</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>outpatient: 6</td>
</tr>
<tr class="even">
<td>pde</td>
<td>pde: 6</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>bylaws: 2</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>press_release: 2</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>rights_instrument: 7 · other: 1</td>
</tr>
</tbody>
</table>
<p><strong>Scores — input_mode_counts</strong></p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>text</td>
<td>120</td>
</tr>
</tbody>
</table>
<p><strong>Scores — sorter</strong></p>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Field</th>
<th>Score</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>failure_insights</td>
<td>mode_counts: {‘subclass_miss’: 37, ‘doc_type_miss’: 1} · n_failed: 38 · failures: [{‘filename’: ‘0001615774-14-000417_s100510_ex3-1.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is filed as Exhibit 3.1 and titled ‘AMENDED AND RESTATED MEMORANDUM AND ARTICLES OF ASSOCIATION’. Its content exclusively details corporate governance structures including the company name, registered office, share capital, director appointments and powers, general meetings, voting procedures, and indemnification. Per rules 32 and 33, this is a corporate record classified under articles_of_incorporation.”}, {‘filename’: ‘0001547903-13-000020_a41specimenclassacommonsto.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘rights_instrument’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a specimen stock certificate for Class A Common Stock of NMI Holdings, Inc., filed as Exhibit 4.1. It functions as an instrument defining the ownership and rights of a securityholder, aligning with the corpus convention for securityholder instruments filed as SEC exhibits. Classified as corporate_record with doc_subclass rights_instrument.’}, {‘filename’: ‘0001469709-14-000003_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS FOR THE REGULATION OF NIGHTFOOD HOLDINGS, INC.’ and labeled as Exhibit 3.2. Its content consists entirely of standard corporate governance provisions governing offices, shareholder and director meetings, officer appointments, and amendment procedures. Per rules 32 and 33, the SEC exhibit wrapper does not change the substantive form, making this a corporate_record classified as bylaws.”}, {‘filename’: ‘0001062993-15-000198_s1011515_ex3z2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘powers_of_attorney’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF REVENUE.COM CORPORATION’ and appears as Exhibit 3.2. Per rule 32, corporate governance records like bylaws filed as SEC exhibits are classified as corporate_record. Per rule 33, the subclass is determined by the document’s own heading, making it ‘bylaws’. Note: contract_subtype must be null for non-contracts, but the schema enum requires a value or null; I will set it to null as instructed.”}, {‘filename’: ‘0001144204-19-043489_tv528080_ex3-2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is labeled Exhibit 3.2 and contains the Organizational Minutes of the Initial Board of Directors followed by the complete text of the ‘BY-LAWS OF INCUMAKER, INC.’ Under rules 32 and 33, corporate governance records such as bylaws filed as SEC exhibits are classified as corporate_record, with the subclass assigned based on the document’s own title and content.”}, {‘filename’: ‘0001079974-08-000839_artdimensionss1x32_9252008.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF ART DIMENSIONS, INC.’ and filed as Exhibit 3.2. Its content consists entirely of standard corporate governance provisions (offices, registered agent, stockholder/board meetings, officers, capital stock, indemnification), which directly matches the corporate_record class and bylaws subclass under rules 32 and 33.”}, {‘filename’: ‘0001615774-14-000417_s100510_ex4-7.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘rights_instrument’}, ‘predicted’: {‘doc_type’: ‘contract’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘doc_type_miss’, ‘reasoning’: “The document is a Unit Purchase Option agreement filed as Exhibit 4.7, detailing the terms, exercise mechanics, transfer restrictions, and registration rights for purchasing units of CB Pharma Acquisition Corp.&nbsp;It constitutes a formal agreement between the issuer and the holder. Because it governs securities purchase rights and does not align with any of the specific enumerated contract families (e.g., license, distribution, service, or endorsement), it is classified as a contract with the subtype ‘other’.”}, {‘filename’: ‘0001144204-19-030811_tv521467_ex3-2.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘articles_of_incorporation’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is filed as SEC Exhibit 3.2 and contains the ‘Organizational Minutes’ and the full text of the ‘By-Laws of Incumaker, Inc.’ Per Rule 32, corporate records such as bylaws attached to an SEC exhibit are classified as corporate_record. Rule 33 directs classifying the subclass based on the document’s own title, which explicitly names the bylaws, making ‘bylaws’ the correct doc_subclass.”}, {‘filename’: ‘0001469709-14-000529_ex3_2apg.htm’, ‘expected’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘powers_of_attorney’}, ‘predicted’: {‘doc_type’: ‘corporate_record’, ‘doc_subclass’: ‘bylaws’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘BYLAWS OF SWEETS &amp; TREATS, INC.’ and filed as Exhibit 3.2. It contains standard internal governance provisions for stockholders, directors, officers, and meeting procedures. Per rules 32 and 33, corporate records like bylaws filed as SEC exhibits are classified as corporate_record with the doc_subclass ‘bylaws’.”}, {‘filename’: ‘shackleton-s/all_documents/3774.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is a business email coordinating the execution and routing of attached notices (Asset Notice, Prepayment Notice, Direction Letter). It features standard email conventions such as ‘Attached to this e-mail,’ direct instructional paragraphs to specific recipients, and contact/fax details. It lacks operative contractual terms, corporate governance language, or M&amp;A/insurance claim structures, firmly placing it in the correspondence class.”}, {‘filename’: ‘hyatt-k/to_do/51.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘demand’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘memo’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a brief administrative record containing only task metadata (status, priority, dates). It lacks substantive legal terms, corporate governance language, or M&amp;A/insurance structures. Given the available classes, it best fits correspondence as an internal memo/note, though extreme brevity limits confidence.’}, {‘filename’: ‘ermis-f/all_documents/303.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘meeting_request’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘letter’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a standalone corporate disclaimer/announcement clarifying the operational and regulatory separation between PG&amp;E National Energy Group and Pacific Gas and Electric Company. It contains no contractual obligations, corporate governance records, M&amp;A transaction mechanics, or insurance claim data. Its formal, informational nature aligns with business correspondence, specifically a letter.’}, {‘filename’: ‘sanders-r/inbox/38.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘meeting_request’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is an informal internal communication discussing litigation preparation, due diligence, and scheduling a meeting with opposing counsel (‘Bid/Ask’). It contains standard email formatting and a confidentiality notice, matching the ‘email’ subclass under correspondence.”}, {‘filename’: ‘campbell-l/inbox/618.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘letter’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a direct customer communication from 1-800 CONTACTS containing a personalized re-order link, instructions to reply or call, and an unsubscribe option, which clearly identifies it as an email correspondence.’}, {‘filename’: ‘sanders-r/px/17.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘attorney_demand’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is an internal forwarding message/email circulating a revised draft of an arbitration demand letter. It lacks any operative contractual terms, corporate governance structure, or M&amp;A deal mechanics. Its informal forwarding language and attachment reference clearly identify it as business correspondence, specifically an email.’}, {‘filename’: ‘shackleton-s/inbox/675.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘memo’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘Notice # 02-46’ and uses a standard TO/FROM/RE format to communicate procedural updates regarding EFP/EFS trade execution to NYMEX members. It functions as a formal regulatory/internal notice rather than a contract, corporate record, or insurance claim.”}, {‘filename’: ‘kean-s/all_documents/1990.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘memo’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a brief business communication/email discussing the distribution of a prepared analysis memo to industry stakeholders and government officials regarding regulatory rule changes. It lacks operative agreement terms, corporate governance records, or claim documentation, clearly matching the correspondence class.’}, {‘filename’: ‘schoolcraft-d/inbox/junk/351.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘demand’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a daily industry newsletter/email digest from Rigzone featuring compiled oil and gas headlines, event listings, advertisements, and subscriber management/unsubscribe instructions. It lacks any contractual, corporate governance, M&amp;A, or insurance claim substance, fitting squarely into the correspondence class as an email broadcast.’}, {‘filename’: ‘storey-g/sent_items/76.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a threaded email exchange between colleagues discussing specific contractual options (delivery point selections) to be added to commodity trading confirmations. Standard email headers (From, Sent, To, Subject) and informal business language clearly identify it as correspondence.’}, {‘filename’: ‘campbell-l/all_documents/1428.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘notice’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is formatted as an email sent to a discussion list (‘writes to the NYISO_TECH_EXCHANGE Discussion List’) announcing routine system maintenance. It contains standard email salutations and sign-offs, lacks any contractual, corporate record, merger, or insurance claim elements, and clearly fits the correspondence class with an email subclass.”}, {‘filename’: ‘kaminski-v/inbox/81.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘letter’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is an informal email thread discussing academic conference attendance and a seminar invitation. It lacks any contractual obligations, corporate governance records, or M&amp;A/insurance structures, clearly fitting the correspondence class as an email.’}, {‘filename’: ‘staab-t/deleted_items/418.’, ‘expected’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘letter’}, ‘predicted’: {‘doc_type’: ‘correspondence’, ‘doc_subclass’: ‘email’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: ‘The document is a direct electronic communication from an American Airlines executive to a specific recipient, providing operational updates and expressing gratitude following the 9/11 attacks. It contains explicit email metadata (Message-ID, unsubscribe instructions, recipient address) and follows a standard business email format, firmly placing it in the correspondence class under the email subclass.’}, {‘filename’: ‘contract_123_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative clauses including a tender offer, merger mechanics, capital stock treatment, representations and warranties, closing conditions, and termination provisions. The consideration is specified as $41.50 per share in cash, making it an all-cash transaction. Embedded exhibits like the Certificate of Incorporation do not alter the primary classification per corpus conventions.”}, {‘filename’: ‘contract_50_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative machinery including Article I (The Mergers), Article II (Effect on Capital Stock), Article III (Payment for Shares in cash at $11.69 and $7.81 per share), along with typical representations, warranties, conditions to closing, and termination provisions. Per Rule 31, this triggers the merger_agreement class. The consideration is exclusively cash, satisfying Rule 33 for doc_subclass all_cash.”}, {‘filename’: ‘contract_119_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative machinery including a ‘Parent’, ‘Merger Subsidiary’, and ‘Company’, along with articles detailing ‘THE MERGER’, ‘Conversion of Shares’, representations, covenants, conditions, and termination. Section 2.02 specifies that shares will be converted for ‘$58.00 in cash’, indicating an all-cash consideration structure. Therefore, it classifies as a merger_agreement with an all_cash subclass.”}, {‘filename’: ‘contract_113_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A machinery including a tender offer, merger mechanics, representations and warranties, covenants, and termination provisions. The consideration section specifies a fixed cash price of $22.50 per share, indicating an all-cash transaction. Per rule 31 and 33, this is classified as a merger_agreement with an all_cash subclass.”}, {‘filename’: ‘contract_69_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and follows the standard structure of a public-company acquisition agreement, featuring parties designated as ‘Company’, ‘Parent’, and ‘Merger Sub’, along with standard M&amp;A articles such as ‘The Merger’, ‘Closing’, ‘Representations and Warranties’, ‘Conditions to Closing’, and termination provisions. The consideration section explicitly defines the ‘Per Share Merger Consideration’ as ‘$156.00 per Share in cash,’ confirming an all-cash deal. This directly triggers rule 31 for merger_agreement and rule 33 for the all_cash subclass.”}, {‘filename’: ‘contract_120_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A structure including Parent/Merger Sub/Company parties, merger mechanics (Effective Time, Closing), extensive representations and warranties, conditions to closing, no-shop covenants, and termination fees. Per Rule 31, this is classified as a merger_agreement. The transaction involves a private equity acquirer (Thoma Bravo) with references to debt and equity financing commitments and lacks any stock exchange ratio or conversion mechanics, indicating an all-cash consideration structure for doc_subclass.”}, {‘filename’: ‘contract_22_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and features standard M&amp;A parties (Company, Parent, Merger Sub). Operative clauses detail merger mechanics, closing procedures, representations and warranties, covenants, and conditions to closing. Section 4.3 specifies the merger consideration as ‘$25.75 per Share in cash,’ indicating an all-cash transaction. Under Rule 31, this title and structure mandate classification as merger_agreement. Under Rule 33, the consideration type is all_cash. Embedded corporate documents like Annex B are annex content per Rule 34.”}, {‘filename’: ‘contract_16_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and follows the standard M&amp;A structure with a Parent/Merger Sub counterparty, articles governing ‘THE MERGER’, ‘EFFECTIVE TIME’, capital stock conversion, representations and warranties, covenants, conditions to closing, and termination rights. Section 3.1(a) specifies that all outstanding shares will convert into the right to receive ‘$56.00 in cash’, confirming an all-cash consideration structure.”}, {‘filename’: ‘contract_110_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative clauses, including parties labeled as ‘Parent,’ ‘Merger Sub,’ and ‘Company,’ along with articles detailing ‘THE MERGER,’ ‘MERGER CONSIDERATION,’ representations, warranties, covenants, closing conditions, and termination fees. This squarely matches the merger_agreement class per Rule 31. The specific consideration breakdown (cash vs.&nbsp;stock) is not fully visible in the provided excerpt, so ‘other’ is assigned for doc_subclass.”}, {‘filename’: ‘contract_93_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative provisions including merger mechanics (Article I), stockholder approval, representations and warranties (Articles III-IV), covenants (Article V), closing conditions (Article VI), and termination fees (Article VII). Section 2.01 specifies that Company Common Stock will be converted into an exchange ratio of Buyer Common Stock, indicating a pure stock-for-stock transaction. This squarely matches the merger_agreement class under rule 31, with an all_stock subclass per rule 33.”}, {‘filename’: ‘contract_68_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A deal structure provisions (Parent/Merger Sub parties, Effective Time mechanics, stock exchange ratio for Merger Consideration, reps &amp; warranties, covenants, conditions precedent). Per Rules 31 and 36, the primary M&amp;A agreement governs the classification despite the inclusion of ancillary documents like a Registration Rights Agreement and Amendment No.&nbsp;1 within the same filing package. The merger consideration consists of shares of Parent Common Stock (with cash only for fractional shares), supporting an all_stock subclass.”}, {‘filename’: ‘contract_141_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative provisions, including a ‘Merger Sub,’ ‘Effective Time,’ share conversion mechanics, extensive representations and warranties, and termination fees. Section 2.1(a) specifies that each share of Company Common Stock will be converted into ‘$177.50 in cash,’ confirming an all-cash consideration structure. Under Rule 31 and Rule 33, this is classified as a merger_agreement with doc_subclass all_cash.”}, {‘filename’: ‘contract_31_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A machinery including a Parent/Merger Sub/Company structure, Effective Time mechanics, Exchange Ratio for stock conversion, extensive representations and warranties, no-shop covenants, and conditions precedent. Per Rule 31, this triggers merger_agreement. Section 3.1 specifies that Company Common Stock will be converted solely into shares of Parent Common Stock at a fixed Exchange Ratio (1.46), with only standard cash-in-lieu-of-fractions provisions, indicating an all-stock consideration, which sets doc_subclass to all_stock per Rule 33.”}, {‘filename’: ‘contract_9_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document title explicitly identifies it as an ‘AMENDED AND RESTATED AGREEMENT AND PLAN OF MERGER’. The operative provisions detail a cash tender offer followed by a statutory merger, including standard M&amp;A machinery such as representations and warranties, covenants, closing conditions, termination rights, and a fixed cash merger consideration ($37.00 per share). Under Rule 31, this falls squarely under merger_agreement. Per Rule 33, the consideration is exclusively cash, making the doc_subclass all_cash.”}, {‘filename’: ‘contract_76_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘mixed_cash_stock’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and contains standard M&amp;A operative clauses including ‘THE MERGERS’, ‘CONVERSION OF SHARES’, representations and warranties, covenants, conditions to closing, and termination provisions. Section 2.1 specifies that shares will be converted into Parent Common Shares plus $90.00 in cash per share, indicating a mixed cash and stock consideration. Per Rules 31 and 33, this is classified as a merger_agreement with doc_subclass mixed_cash_stock.”}, {‘filename’: ‘contract_59_merger_agreement.txt’, ‘expected’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘other’}, ‘predicted’: {‘doc_type’: ‘merger_agreement’, ‘doc_subclass’: ‘all_cash’}, ‘failure_mode’: ‘subclass_miss’, ‘reasoning’: “The document is explicitly titled ‘AGREEMENT AND PLAN OF MERGER’ and follows the standard structure of a corporate acquisition agreement, featuring a ‘Parent’, ‘Merger Sub’, and ‘Company’ counterparty, along with articles covering the merger mechanics, capital stock conversion, representations and warranties, covenants, and closing conditions. Section 2.1(a) explicitly states that each share will be converted into the right to receive ‘$19.25 in cash’, confirming an all-cash consideration structure. This squarely fits the merger_agreement class with an all_cash subclass.”}]</td>
</tr>
</tbody>
</table>
</section>
<section id="per-subclass-accuracy-second-level-dimension-3" class="level3">
<h3 class="anchored" data-anchor-id="per-subclass-accuracy-second-level-dimension-3">Per-subclass accuracy (second-level dimension)</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>subclass</th>
<th>accuracy</th>
<th>support (rows with GT)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Agency Agreements</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Co_Branding</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Collaboration</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td>Endorsement</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Franchise</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Hosting</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="odd">
<td>License_Agreements</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Outsourcing</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Reseller</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>Sponsorship</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="odd">
<td>Strategic Alliance</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>Supply</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Transportation</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="even">
<td>all_cash</td>
<td>0.8</td>
<td>5</td>
</tr>
<tr class="odd">
<td>all_stock</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="even">
<td>articles_of_incorporation</td>
<td>0.5833</td>
<td>12</td>
</tr>
<tr class="odd">
<td>attorney_demand</td>
<td>0.0</td>
<td>1</td>
</tr>
<tr class="even">
<td>bylaws</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>carrier</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td>demand</td>
<td>0.0</td>
<td>2</td>
</tr>
<tr class="odd">
<td>email</td>
<td>1</td>
<td>4</td>
</tr>
<tr class="even">
<td>inpatient</td>
<td>1</td>
<td>8</td>
</tr>
<tr class="odd">
<td>letter</td>
<td>0.4</td>
<td>5</td>
</tr>
<tr class="even">
<td>meeting_request</td>
<td>0.3333</td>
<td>3</td>
</tr>
<tr class="odd">
<td>memo</td>
<td>0.0</td>
<td>2</td>
</tr>
<tr class="even">
<td>mixed_cash_stock</td>
<td>1</td>
<td>1</td>
</tr>
<tr class="odd">
<td>notice</td>
<td>0.4</td>
<td>5</td>
</tr>
<tr class="even">
<td>other</td>
<td>0.0588</td>
<td>17</td>
</tr>
<tr class="odd">
<td>outpatient</td>
<td>1</td>
<td>6</td>
</tr>
<tr class="even">
<td>pde</td>
<td>1</td>
<td>6</td>
</tr>
<tr class="odd">
<td>powers_of_attorney</td>
<td>0.0</td>
<td>2</td>
</tr>
<tr class="even">
<td>press_release</td>
<td>1</td>
<td>2</td>
</tr>
<tr class="odd">
<td>rights_instrument</td>
<td>1</td>
<td>8</td>
</tr>
</tbody>
</table>
<ul>
<li><p>subclass_accuracy_equiv: 0.6833 — strict subclass OR a defensible equivalent family (mixed_cash_stock ↔︎ mixed_cash_stock_election); equiv-recovered rows: none</p></li>
<li><p>input-mode split: text 120</p></li>
</ul>
<hr>
</section>
</section>
<section id="qwen_qwen3.7-flash_contracts_specialist_docclass_v0_docclass_ab120_s42-docclass_specialist_extraction" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_contracts_specialist_docclass_v0_docclass_ab120_s42-docclass_specialist_extraction">qwen_qwen3.7-flash_contracts_specialist_docclass_v0_docclass_ab120_s42 (docclass_specialist_extraction)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/5">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata-4" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata-4">Run metadata</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T18:57:55.585037+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>contracts_specialist: contracts_specialist_docclass_v0</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>388c466</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source-4" class="level3">
<h3 class="anchored" data-anchor-id="data-source-4">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>local_dumps</td>
<td>data/datasets/docclass_merged_v5.jsonl</td>
</tr>
<tr class="even">
<td>agent</td>
<td>contracts_specialist</td>
</tr>
<tr class="odd">
<td>ground_truth</td>
<td>docclass_merged_v5_gt_fields</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>34083b161a915165e1a4c6a0cfa01324f15d8310bf20427cea1e893dc4e1acec</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_routed</td>
<td>48</td>
</tr>
<tr class="odd">
<td>filename_manifest</td>
<td>data/manifests/docclass_ab120_s42_filenames.jsonl</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters-4" class="level3">
<h3 class="anchored" data-anchor-id="parameters-4">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>agent</td>
<td>contracts_specialist</td>
</tr>
<tr class="even">
<td>prompt_version</td>
<td>contracts_specialist_docclass_v0</td>
</tr>
<tr class="odd">
<td>chunked</td>
<td>✓</td>
</tr>
<tr class="even">
<td>max_input_chars</td>
<td>150000</td>
</tr>
<tr class="odd">
<td>max_tokens</td>
<td>32768</td>
</tr>
<tr class="even">
<td>reasoning_effort</td>
<td>none</td>
</tr>
<tr class="odd">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="even">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="odd">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_contracts_specialist_docclass_v0_docclass_ab120_s42 · trace_name: docclass_specialist_extraction · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage-4" class="level3">
<h3 class="anchored" data-anchor-id="token-usage-4">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores-4" class="level3">
<h3 class="anchored" data-anchor-id="scores-4">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>overall_extraction_score</td>
<td>0.6884</td>
</tr>
<tr class="even">
<td>field_presence</td>
<td>0.9502</td>
</tr>
<tr class="odd">
<td>overall_verified_precision</td>
<td>0.9888</td>
</tr>
<tr class="even">
<td>category_presence</td>
<td>0.3588</td>
</tr>
<tr class="odd">
<td>n_rows</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="odd">
<td>n_routed</td>
<td>48</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="qwen_qwen3.7-flash_contracts_specialist_docclass_v1_docclass_ab120_s42-docclass_specialist_extraction" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_contracts_specialist_docclass_v1_docclass_ab120_s42-docclass_specialist_extraction">qwen_qwen3.7-flash_contracts_specialist_docclass_v1_docclass_ab120_s42 (docclass_specialist_extraction)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/6">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata-5" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata-5">Run metadata</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T18:59:54.737881+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>contracts_specialist: contracts_specialist_docclass_v1</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>388c466</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source-5" class="level3">
<h3 class="anchored" data-anchor-id="data-source-5">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>local_dumps</td>
<td>data/datasets/docclass_merged_v5.jsonl</td>
</tr>
<tr class="even">
<td>agent</td>
<td>contracts_specialist</td>
</tr>
<tr class="odd">
<td>ground_truth</td>
<td>docclass_merged_v5_gt_fields</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>34083b161a915165e1a4c6a0cfa01324f15d8310bf20427cea1e893dc4e1acec</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_routed</td>
<td>48</td>
</tr>
<tr class="odd">
<td>filename_manifest</td>
<td>data/manifests/docclass_ab120_s42_filenames.jsonl</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters-5" class="level3">
<h3 class="anchored" data-anchor-id="parameters-5">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>agent</td>
<td>contracts_specialist</td>
</tr>
<tr class="even">
<td>prompt_version</td>
<td>contracts_specialist_docclass_v1</td>
</tr>
<tr class="odd">
<td>chunked</td>
<td>✓</td>
</tr>
<tr class="even">
<td>max_input_chars</td>
<td>150000</td>
</tr>
<tr class="odd">
<td>max_tokens</td>
<td>32768</td>
</tr>
<tr class="even">
<td>reasoning_effort</td>
<td>none</td>
</tr>
<tr class="odd">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="even">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="odd">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_contracts_specialist_docclass_v1_docclass_ab120_s42 · trace_name: docclass_specialist_extraction · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage-5" class="level3">
<h3 class="anchored" data-anchor-id="token-usage-5">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores-5" class="level3">
<h3 class="anchored" data-anchor-id="scores-5">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>overall_extraction_score</td>
<td>0.8444</td>
</tr>
<tr class="even">
<td>field_presence</td>
<td>0.9562</td>
</tr>
<tr class="odd">
<td>overall_verified_precision</td>
<td>0.968</td>
</tr>
<tr class="even">
<td>category_presence</td>
<td>0.7449</td>
</tr>
<tr class="odd">
<td>n_rows</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="odd">
<td>n_routed</td>
<td>48</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v0_docclass_ab120_s42-docclass_specialist_extraction" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v0_docclass_ab120_s42-docclass_specialist_extraction">qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v0_docclass_ab120_s42 (docclass_specialist_extraction)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/7">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata-6" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata-6">Run metadata</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T19:00:07.283289+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>insurance_claims_specialist: insurance_claims_specialist_docclass_v0</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>388c466</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source-6" class="level3">
<h3 class="anchored" data-anchor-id="data-source-6">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>local_dumps</td>
<td>data/datasets/docclass_merged_v5.jsonl</td>
</tr>
<tr class="even">
<td>agent</td>
<td>insurance_claims_specialist</td>
</tr>
<tr class="odd">
<td>ground_truth</td>
<td>docclass_merged_v5_gt_fields</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>b238c80e946cfa0ece004c0129708a233e129f0168d7f02cf7002f78c45133ac</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_routed</td>
<td>24</td>
</tr>
<tr class="odd">
<td>filename_manifest</td>
<td>data/manifests/docclass_ab120_s42_filenames.jsonl</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters-6" class="level3">
<h3 class="anchored" data-anchor-id="parameters-6">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>agent</td>
<td>insurance_claims_specialist</td>
</tr>
<tr class="even">
<td>prompt_version</td>
<td>insurance_claims_specialist_docclass_v0</td>
</tr>
<tr class="odd">
<td>chunked</td>
<td>✗</td>
</tr>
<tr class="even">
<td>max_input_chars</td>
<td>150000</td>
</tr>
<tr class="odd">
<td>max_tokens</td>
<td>32768</td>
</tr>
<tr class="even">
<td>reasoning_effort</td>
<td>none</td>
</tr>
<tr class="odd">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="even">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="odd">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v0_docclass_ab120_s42 · trace_name: docclass_specialist_extraction · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage-6" class="level3">
<h3 class="anchored" data-anchor-id="token-usage-6">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores-6" class="level3">
<h3 class="anchored" data-anchor-id="scores-6">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>overall_extraction_score</td>
<td>0.6957</td>
</tr>
<tr class="even">
<td>field_presence</td>
<td>0.7311</td>
</tr>
<tr class="odd">
<td>overall_verified_precision</td>
<td>1</td>
</tr>
<tr class="even">
<td>category_presence</td>
<td>—</td>
</tr>
<tr class="odd">
<td>n_rows</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="odd">
<td>n_routed</td>
<td>24</td>
</tr>
</tbody>
</table>
<hr>
</section>
</section>
<section id="qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v1_docclass_ab120_s42-docclass_specialist_extraction" class="level2">
<h2 class="anchored" data-anchor-id="qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v1_docclass_ab120_s42-docclass_specialist_extraction">qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v1_docclass_ab120_s42 (docclass_specialist_extraction)</h2>
<blockquote class="blockquote">
<p><a href="../index.html#/run/8">Interactive explorer detail →</a></p>
</blockquote>
<section id="run-metadata-7" class="level3">
<h3 class="anchored" data-anchor-id="run-metadata-7">Run metadata</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Timestamp</td>
<td>2026-08-26T19:00:19.960201+00:00</td>
</tr>
<tr class="even">
<td>Model</td>
<td>qwen/qwen3.7-flash</td>
</tr>
<tr class="odd">
<td>Prompt version</td>
<td>insurance_claims_specialist: insurance_claims_specialist_docclass_v1</td>
</tr>
<tr class="even">
<td>Git commit</td>
<td><code>388c466</code> (dirty tree)</td>
</tr>
</tbody>
</table>
</section>
<section id="data-source-7" class="level3">
<h3 class="anchored" data-anchor-id="data-source-7">Data source</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>local_dumps</td>
<td>data/datasets/docclass_merged_v5.jsonl</td>
</tr>
<tr class="even">
<td>agent</td>
<td>insurance_claims_specialist</td>
</tr>
<tr class="odd">
<td>ground_truth</td>
<td>docclass_merged_v5_gt_fields</td>
</tr>
<tr class="even">
<td>dataset_fingerprint</td>
<td>b238c80e946cfa0ece004c0129708a233e129f0168d7f02cf7002f78c45133ac</td>
</tr>
<tr class="odd">
<td>n_samples</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_routed</td>
<td>24</td>
</tr>
<tr class="odd">
<td>filename_manifest</td>
<td>data/manifests/docclass_ab120_s42_filenames.jsonl</td>
</tr>
<tr class="even">
<td>seed</td>
<td>42</td>
</tr>
<tr class="odd">
<td>stratified</td>
<td>0</td>
</tr>
</tbody>
</table>
</section>
<section id="parameters-7" class="level3">
<h3 class="anchored" data-anchor-id="parameters-7">Parameters</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Key</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>agent</td>
<td>insurance_claims_specialist</td>
</tr>
<tr class="even">
<td>prompt_version</td>
<td>insurance_claims_specialist_docclass_v1</td>
</tr>
<tr class="odd">
<td>chunked</td>
<td>✗</td>
</tr>
<tr class="even">
<td>max_input_chars</td>
<td>150000</td>
</tr>
<tr class="odd">
<td>max_tokens</td>
<td>32768</td>
</tr>
<tr class="even">
<td>reasoning_effort</td>
<td>none</td>
</tr>
<tr class="odd">
<td>temperature</td>
<td>0.1</td>
</tr>
<tr class="even">
<td>tracing_backend</td>
<td>langfuse</td>
</tr>
<tr class="odd">
<td>tracing_meta</td>
<td>project: llm-dojo · environment: llm-dojo · base_url: https://us.cloud.langfuse.com · session_id: qwen_qwen3.7-flash_insurance_claims_specialist_docclass_v1_docclass_ab120_s42 · trace_name: docclass_specialist_extraction · disabled: False</td>
</tr>
</tbody>
</table>
</section>
<section id="token-usage-7" class="level3">
<h3 class="anchored" data-anchor-id="token-usage-7">Token usage</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Stage</th>
<th>Prompt</th>
<th>Completion</th>
<th>Total</th>
<th>Mean cost $</th>
<th>Total cost $</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>all</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
<td>—</td>
</tr>
</tbody>
</table>
</section>
<section id="scores-7" class="level3">
<h3 class="anchored" data-anchor-id="scores-7">Scores</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>overall_extraction_score</td>
<td>0.6904</td>
</tr>
<tr class="even">
<td>field_presence</td>
<td>0.7273</td>
</tr>
<tr class="odd">
<td>overall_verified_precision</td>
<td>1</td>
</tr>
<tr class="even">
<td>category_presence</td>
<td>—</td>
</tr>
<tr class="odd">
<td>n_rows</td>
<td>24</td>
</tr>
<tr class="even">
<td>n_errors</td>
<td>0</td>
</tr>
<tr class="odd">
<td>n_routed</td>
<td>24</td>
</tr>
</tbody>
</table>
<hr>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
            // default icon
            link.classList.add("external");
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>llm-entity-extraction · Posit Cloud portal</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
<p>derived from <span class="mono">reports/experiment_log.jsonl</span>, <span class="mono">board/MESSAGE_BOARD.md</span> and <span class="mono">discussion/MESSAGE_BOARD_DISCUSSION.qmd</span> — never hand-edited</p>
</div>
  </div>
</footer>




</body></html>